# Generated by Django 3.2.6 on 2021-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Id', models.IntegerField(max_length=10)),
                ('StudentName', models.CharField(max_length=50)),
                ('Semester', models.CharField(max_length=5)),
                ('Branch', models.CharField(max_length=5)),
                ('Year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentLoginForm',
        ),
    ]
