# Generated by Django 3.2.6 on 2021-08-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210815_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
